/**
 * Proteus2 Design Tokens — React Native
 *
 * Phase 1: Hand-crafted from tokens.css primitives and semantics.
 * Phase 2: Generated by Style Dictionary from DTCG JSON source.
 *
 * Each semantic token comment names its CSS counterpart so Phase 2
 * mapping is mechanical — same token, different output format.
 *
 * Usage:
 *   import { COLORS, SPACING, FONT_SIZE, FONT_WEIGHT, BORDER_RADIUS, SIZE } from './tokens.rn';
 *
 *   const scheme = useColorScheme() ?? 'light';
 *   const colors = COLORS[scheme];
 */

// =============================================================================
// PRIMITIVE COLORS
// Do NOT import in components — use COLORS[scheme] instead.
// Source: tokens.css — Section 1 (OKLCH values converted to hex for RN)
// =============================================================================

export const PRIMITIVE_COLORS = {
  neutral: {
    50:  "#fafafa",
    100: "#f4f4f5",
    200: "#e4e4e7",
    300: "#d4d4d8",
    400: "#9f9fa9",
    500: "#71717b",
    600: "#52525c",
    700: "#3f3f46",
    800: "#27272a",
    900: "#18181b",
    950: "#09090b",
  },
  // Custom brand scale, OKLCH hue 43.7 (warm orange). Only this ramp
  // changes per tenant — same variable names, different values.
  brand: {
    50:  "#fcf7f5",
    100: "#f9ebe6",
    200: "#f8d7c9",
    300: "#f7b99f",
    400: "#f78857",
    500: "#df6427",
    600: "#c65821",
    700: "#a14619",
    800: "#863913",
    900: "#712f0f",
    950: "#451a05",
  },
  red: {
    50:  "#fef2f2",
    100: "#ffe2e2",
    200: "#ffc9c9",
    300: "#ffa2a2",
    400: "#ff6467",
    500: "#fb2c36",
    600: "#e7000b",
    700: "#c10007",
    800: "#9f0712",
    900: "#82181a",
    950: "#460809",
  },
  yellow: {
    50:  "#fefce8",
    100: "#fef9c2",
    200: "#fff085",
    300: "#ffdf20",
    400: "#fdc700",
    500: "#f0b100",
    600: "#d08700",
    700: "#a65f00",
    800: "#894b00",
    900: "#733e0a",
    950: "#432004",
  },
  emerald: {
    50:  "#ecfdf5",
    100: "#d0fae5",
    200: "#a4f4cf",
    300: "#5ee9b5",
    400: "#00d492",
    500: "#00bc7d",
    600: "#009966",
    700: "#007a55",
    800: "#006045",
    900: "#004f3b",
    950: "#002c22",
  },
  sky: {
    50:  "#f0f9ff",
    100: "#dff2fe",
    200: "#b8e6fe",
    300: "#74d4ff",
    400: "#00bcff",
    500: "#00a6f4",
    600: "#0084d1",
    700: "#0069a8",
    800: "#00598a",
    900: "#024a70",
    950: "#052f4a",
  },
  white: "#ffffff",
  black: "#000000",
} as const;

// =============================================================================
// SEMANTIC COLORS
// Source: tokens.css — Sections 2 (light) and 3 (dark)
// =============================================================================

export const COLORS = {
  light: {
    // --- Surfaces ---
    background:                    "#ffffff",  // --pcs-color-background
    surfaceCard:                   "#ffffff",  // --pcs-color-surface-card
    surfaceMuted:                  "#f4f4f5",  // --pcs-color-surface-muted       (neutral-100)
    surfaceOverlay:                "#ffffff",  // --pcs-color-surface-overlay
    surfaceSidebar:                "#fafafa",  // --pcs-color-surface-sidebar      (neutral-50)

    // --- Borders ---
    borderDefault:                 "#e4e4e7",  // --pcs-color-border-default       (neutral-200)
    borderMuted:                   "#f4f4f5",  // --pcs-color-border-muted         (neutral-100)
    borderStrong:                  "#d4d4d8",  // --pcs-color-border-strong        (neutral-300)
    borderDisabled:                "#e4e4e7",  // --pcs-color-border-disabled      (neutral-200)

    // --- Text ---
    textDefault:                   "#18181b",  // --pcs-color-text-default         (neutral-900)
    textMuted:                     "#71717b",  // --pcs-color-text-muted           (neutral-500)
    textDisabled:                  "#d4d4d8",  // --pcs-color-text-disabled        (neutral-300)
    textInverse:                   "#ffffff",  // --pcs-color-text-inverse
    textOnEmphasis:                "#ffffff",  // --pcs-color-text-on-emphasis

    // --- Icons ---
    iconDefault:                   "#52525c",  // --pcs-color-icon-default         (neutral-600)
    iconMuted:                     "#9f9fa9",  // --pcs-color-icon-muted           (neutral-400)
    iconDisabled:                  "#d4d4d8",  // --pcs-color-icon-disabled        (neutral-300)

    // --- Primary / Brand ---
    primaryEmphasis:               "#c65821",  // --pcs-color-primary-emphasis     (brand-600)
    primaryEmphasisHover:          "#a14619",  // --pcs-color-primary-emphasis-hover (brand-700)
    primaryEmphasisActive:         "#863913",  // --pcs-color-primary-emphasis-active (brand-800)
    primarySubtle:                 "#fcf7f5",  // --pcs-color-primary-subtle       (brand-50)
    primarySubtleHover:            "#f9ebe6",  // --pcs-color-primary-subtle-hover (brand-100)
    primaryText:                   "#863913",  // --pcs-color-primary-text         (brand-800)
    primaryBorder:                 "#f7b99f",  // --pcs-color-primary-border       (brand-300)
    primaryIcon:                   "#c65821",  // --pcs-color-primary-icon         (brand-600)
    primaryOnEmphasis:             "#ffffff",  // --pcs-color-primary-on-emphasis
    focusRing:                     "#f78857",  // --pcs-color-focus-ring           (brand-400)

    // --- Interactive states ---
    surfaceNeutralHover:           "#f4f4f5",  // --pcs-color-surface-neutral-hover  (neutral-100)
    surfaceNeutralActive:          "#e4e4e7",  // --pcs-color-surface-neutral-active (neutral-200)
    surfaceNeutralSelected:        "#fcf7f5",  // --pcs-color-surface-neutral-selected (brand-50)
    surfaceNeutralSelectedBorder:  "#f78857",  // --pcs-color-surface-neutral-selected-border (brand-400)
    surfaceDisabled:               "#f4f4f5",  // --pcs-color-surface-disabled     (neutral-100)

    // --- Success ---
    successBackground:             "#ecfdf5",  // --pcs-color-success-background   (emerald-50)
    successBackgroundHover:        "#d0fae5",  // --pcs-color-success-background-hover (emerald-100)
    successBorder:                 "#a4f4cf",  // --pcs-color-success-border       (emerald-200)
    successText:                   "#006045",  // --pcs-color-success-text         (emerald-800)
    successIcon:                   "#007a55",  // --pcs-color-success-icon         (emerald-700)
    successEmphasis:               "#009966",  // --pcs-color-success-emphasis     (emerald-600)
    successOnEmphasis:             "#ffffff",  // --pcs-color-success-on-emphasis

    // --- Error ---
    errorBackground:               "#fef2f2",  // --pcs-color-error-background     (red-50)
    errorBackgroundHover:          "#ffe2e2",  // --pcs-color-error-background-hover (red-100)
    errorBorder:                   "#ffa2a2",  // --pcs-color-error-border         (red-300)
    errorText:                     "#c10007",  // --pcs-color-error-text           (red-700)
    errorIcon:                     "#c10007",  // --pcs-color-error-icon           (red-700)
    errorEmphasis:                 "#e7000b",  // --pcs-color-error-emphasis       (red-600)
    errorOnEmphasis:               "#ffffff",  // --pcs-color-error-on-emphasis

    // --- Warning ---
    warningBackground:             "#fefce8",  // --pcs-color-warning-background   (yellow-50)
    warningBackgroundHover:        "#fef9c2",  // --pcs-color-warning-background-hover (yellow-100)
    warningBorder:                 "#ffdf20",  // --pcs-color-warning-border       (yellow-300)
    warningText:                   "#894b00",  // --pcs-color-warning-text         (yellow-800)
    warningIcon:                   "#a65f00",  // --pcs-color-warning-icon         (yellow-700)
    warningEmphasis:               "#f0b100",  // --pcs-color-warning-emphasis     (yellow-500)
    warningOnEmphasis:             "#09090b",  // --pcs-color-warning-on-emphasis  (neutral-950)

    // --- Info ---
    infoBackground:                "#f0f9ff",  // --pcs-color-info-background      (sky-50)
    infoBackgroundHover:           "#dff2fe",  // --pcs-color-info-background-hover (sky-100)
    infoBorder:                    "#b8e6fe",  // --pcs-color-info-border          (sky-200)
    infoText:                      "#00598a",  // --pcs-color-info-text            (sky-800)
    infoIcon:                      "#0069a8",  // --pcs-color-info-icon            (sky-700)
    infoEmphasis:                  "#0084d1",  // --pcs-color-info-emphasis        (sky-600)
    infoOnEmphasis:                "#ffffff",  // --pcs-color-info-on-emphasis
  },

  dark: {
    // --- Surfaces ---
    background:                    "#09090b",  // --pcs-color-background           (neutral-950)
    surfaceCard:                   "#18181b",  // --pcs-color-surface-card         (neutral-900)
    surfaceMuted:                  "#27272a",  // --pcs-color-surface-muted        (neutral-800)
    surfaceOverlay:                "#27272a",  // --pcs-color-surface-overlay      (neutral-800)
    surfaceSidebar:                "#18181b",  // --pcs-color-surface-sidebar      (neutral-900)

    // --- Borders ---
    borderDefault:                 "#3f3f46",  // --pcs-color-border-default       (neutral-700)
    borderMuted:                   "#27272a",  // --pcs-color-border-muted         (neutral-800)
    borderStrong:                  "#52525c",  // --pcs-color-border-strong        (neutral-600)
    borderDisabled:                "#3f3f46",  // --pcs-color-border-disabled      (neutral-700)

    // --- Text ---
    textDefault:                   "#fafafa",  // --pcs-color-text-default         (neutral-50)
    textMuted:                     "#9f9fa9",  // --pcs-color-text-muted           (neutral-400)
    textDisabled:                  "#52525c",  // --pcs-color-text-disabled        (neutral-600)
    textInverse:                   "#09090b",  // --pcs-color-text-inverse         (neutral-950)
    textOnEmphasis:                "#ffffff",  // --pcs-color-text-on-emphasis

    // --- Icons ---
    iconDefault:                   "#9f9fa9",  // --pcs-color-icon-default         (neutral-400)
    iconMuted:                     "#71717b",  // --pcs-color-icon-muted           (neutral-500)
    iconDisabled:                  "#52525c",  // --pcs-color-icon-disabled        (neutral-600)

    // --- Primary / Brand ---
    primaryEmphasis:               "#f78857",  // --pcs-color-primary-emphasis     (brand-400)
    primaryEmphasisHover:          "#f7b99f",  // --pcs-color-primary-emphasis-hover (brand-300)
    primaryEmphasisActive:         "#f8d7c9",  // --pcs-color-primary-emphasis-active (brand-200)
    primarySubtle:                 "#451a05",  // --pcs-color-primary-subtle       (brand-950)
    primarySubtleHover:            "#712f0f",  // --pcs-color-primary-subtle-hover (brand-900)
    primaryText:                   "#f7b99f",  // --pcs-color-primary-text         (brand-300)
    primaryBorder:                 "#a14619",  // --pcs-color-primary-border       (brand-700)
    primaryIcon:                   "#f78857",  // --pcs-color-primary-icon         (brand-400)
    primaryOnEmphasis:             "#09090b",  // --pcs-color-primary-on-emphasis  (neutral-950)
    focusRing:                     "#df6427",  // --pcs-color-focus-ring           (brand-500)

    // --- Interactive states ---
    surfaceNeutralHover:           "#27272a",  // --pcs-color-surface-neutral-hover  (neutral-800)
    surfaceNeutralActive:          "#3f3f46",  // --pcs-color-surface-neutral-active (neutral-700)
    surfaceNeutralSelected:        "#451a05",  // --pcs-color-surface-neutral-selected (brand-950)
    surfaceNeutralSelectedBorder:  "#c65821",  // --pcs-color-surface-neutral-selected-border (brand-600)
    surfaceDisabled:               "#27272a",  // --pcs-color-surface-disabled     (neutral-800)

    // --- Success ---
    successBackground:             "#002c22",  // --pcs-color-success-background   (emerald-950)
    successBackgroundHover:        "#004f3b",  // --pcs-color-success-background-hover (emerald-900)
    successBorder:                 "#004f3b",  // --pcs-color-success-border       (emerald-900)
    successText:                   "#a4f4cf",  // --pcs-color-success-text         (emerald-200)
    successIcon:                   "#00d492",  // --pcs-color-success-icon         (emerald-400)
    successEmphasis:               "#00bc7d",  // --pcs-color-success-emphasis     (emerald-500)
    successOnEmphasis:             "#ffffff",  // --pcs-color-success-on-emphasis

    // --- Error ---
    errorBackground:               "#460809",  // --pcs-color-error-background     (red-950)
    errorBackgroundHover:          "#82181a",  // --pcs-color-error-background-hover (red-900)
    errorBorder:                   "#82181a",  // --pcs-color-error-border         (red-900)
    errorText:                     "#ffa2a2",  // --pcs-color-error-text           (red-300)
    errorIcon:                     "#ff6467",  // --pcs-color-error-icon           (red-400)
    errorEmphasis:                 "#fb2c36",  // --pcs-color-error-emphasis       (red-500)
    errorOnEmphasis:               "#ffffff",  // --pcs-color-error-on-emphasis

    // --- Warning ---
    warningBackground:             "#432004",  // --pcs-color-warning-background   (yellow-950)
    warningBackgroundHover:        "#733e0a",  // --pcs-color-warning-background-hover (yellow-900)
    warningBorder:                 "#733e0a",  // --pcs-color-warning-border       (yellow-900)
    warningText:                   "#fef9c2",  // --pcs-color-warning-text         (yellow-100)
    warningIcon:                   "#fef9c2",  // --pcs-color-warning-icon         (yellow-100)
    warningEmphasis:               "#f0b100",  // --pcs-color-warning-emphasis     (yellow-500)
    warningOnEmphasis:             "#09090b",  // --pcs-color-warning-on-emphasis  (neutral-950)

    // --- Info ---
    infoBackground:                "#052f4a",  // --pcs-color-info-background      (sky-950)
    infoBackgroundHover:           "#024a70",  // --pcs-color-info-background-hover (sky-900)
    infoBorder:                    "#024a70",  // --pcs-color-info-border          (sky-900)
    infoText:                      "#b8e6fe",  // --pcs-color-info-text            (sky-200)
    infoIcon:                      "#00bcff",  // --pcs-color-info-icon            (sky-400)
    infoEmphasis:                  "#00a6f4",  // --pcs-color-info-emphasis        (sky-500)
    infoOnEmphasis:                "#ffffff",  // --pcs-color-info-on-emphasis
  },
} as const;

// =============================================================================
// SPACING
// Source: tokens.css — Section 1.12 (4px base unit)
// Values in dp (density-independent pixels).
// =============================================================================

export const SPACING = {
  0:    0,
  px:   1,
  0.5:  2,
  1:    4,
  1.5:  6,
  2:    8,
  2.5:  10,
  3:    12,
  3.5:  14,
  4:    16,
  5:    20,
  6:    24,
  7:    28,
  8:    32,
  10:   40,
  12:   48,
  14:   56,
  16:   64,
} as const;

// =============================================================================
// FONT SIZE
// Source: tokens.css — Section 1.9
// Values in sp (scale-independent pixels). Base: 1rem = 16sp.
// =============================================================================

export const FONT_SIZE = {
  xs:    12,  // --pcs-primitive-font-size-xs   (0.75rem)
  sm:    14,  // --pcs-primitive-font-size-sm   (0.875rem) — app default body
  base:  16,  // --pcs-primitive-font-size-base (1rem)
  lg:    18,  // --pcs-primitive-font-size-lg   (1.125rem)
  xl:    20,  // --pcs-primitive-font-size-xl   (1.25rem)
  "2xl": 24,  // --pcs-primitive-font-size-2xl  (1.5rem)
  "3xl": 30,  // --pcs-primitive-font-size-3xl  (1.875rem)
  "4xl": 36,  // --pcs-primitive-font-size-4xl  (2.25rem)
} as const;

// =============================================================================
// FONT WEIGHT
// Source: tokens.css — Section 1.10
// =============================================================================

export const FONT_WEIGHT = {
  normal:   "400",  // --pcs-primitive-font-weight-normal
  medium:   "500",  // --pcs-primitive-font-weight-medium
  semiBold: "600",  // --pcs-primitive-font-weight-semibold
  bold:     "700",  // --pcs-primitive-font-weight-bold
} as const;

// =============================================================================
// BORDER RADIUS
// Source: tokens.css — Sections 1.13 + 2.15
// Values in dp.
// =============================================================================

export const BORDER_RADIUS = {
  none:  0,     // --pcs-radius-none
  sm:    2,     // --pcs-radius-sm  (0.125rem)
  md:    6,     // --pcs-radius-md  (0.375rem)
  lg:    8,     // --pcs-radius-lg  (0.5rem)
  xl:    12,    // --pcs-radius-xl  (0.75rem)
  "2xl": 16,    // --pcs-radius-2xl (1rem)
  full:  9999,  // --pcs-radius-full
} as const;

// =============================================================================
// SIZE
// Source: tokens.css — Section 2.13
// Control heights, icon sizes, avatar dimensions. Values in dp.
// =============================================================================

export const SIZE = {
  control: {
    xs: 24,  // --pcs-size-control-xs (space-6)
    sm: 28,  // --pcs-size-control-sm (space-7)
    md: 32,  // --pcs-size-control-md (space-8) — default
    lg: 40,  // --pcs-size-control-lg (space-10)
    xl: 48,  // --pcs-size-control-xl (space-12)
  },
  avatar: {
    xs: 20,  // --pcs-size-avatar-xs  (space-5)
    sm: 24,  // --pcs-size-avatar-sm  (space-6)
    md: 32,  // --pcs-size-avatar-md  (space-8)
    lg: 40,  // --pcs-size-avatar-lg  (space-10)
    xl: 48,  // --pcs-size-avatar-xl  (space-12)
  },
  icon: {
    sm: 12,  // --pcs-size-icon-sm    (space-3)
    md: 16,  // --pcs-size-icon-md    (space-4)
    lg: 20,  // --pcs-size-icon-lg    (space-5)
  },
} as const;
